### ISSUE TITLE
中文乱码问题还是存在问题

### ISSUE THREAD

**Issue by gttiankai** [eggcaker/jekyll-test#1]
我直接git clone 你的jekyll-test中的代码,到本地,然后再目录中运行 jekyll server,启动jekyll,在浏览器中打开http://localhost:4000/2015/04/30/welcom-org.html ,也就是 org生成的那个页面还是会存在中文的乱码问题.
真的是非常奇怪
我的系统是 mac 10.9
emacs version: 24.4.1

**Comment by eggcaker** [comment]
你是用中文的系统吗？

**Comment by eggcaker** [comment]
中文的问题解决了吗？
